### PR TITLE
Fix module support so that it can handle 'clear all' & further operator changes

### PR DESCRIPTION
**Pull request by dcb210**

### CODE REVIEW

**Comment by dcb210** [comment]
You'll need to undo the revert in order to merge.

**Comment by jaeandersson** [comment]
> You'll need to undo the revert in order to merge.

OK, no problem.

**Comment by jaeandersson** [comment]
I think the introduction of `static swig_module_info *saved_swig_module = 0` makes a lot of sense.

I have only one concern left, namely that there will be significant calling overhead (I know some people care a lot about this). I have an idea of how to solve that though.

I will merge in the coming days.

**Comment by jaeandersson** [comment]
I think that a getter-setter function could be added to SwigRef as follows:

``` matlab
classdef SwigRef < handle
  properties 
    swigPtr
  end
  methods
    function disp(self)
      disp(sprintf('<Swig object, ptr=%d>',self.swigPtr))
    end
  end
  methods(Static)
    function varargout = SWIG_module_mem(varargin)
      persistent mem
      mlock
      narginchk(0,1)
      if nargin==0
        nargoutchk(0,1)
        varargout{1} = mem;
      else
        nargoutchk(0,0)
        mem = varargin{1};
      end
    end
  end
end
```

I think that the persistent/mlock combination will prevent deletion, also when doing `clean all`. It is also better encapsulated than the global variable in my opinion.

Internally, I think we could remove the calls to mexGetVariable, mexSetVariable and instead use the `saved_swig_module` variable you just added:

``` c++
static swig_module_info *saved_swig_module = 0;
```

This will save considerable calling overhead. If null (i.e. on first call), it will call SwigRef.SWIG_module_mem. If SwigRef.SWIG_module_mem returns an empty matrix it is the first module to be loaded and SwigRef.SWIG_module_mem will be called again to set the variable.

**Comment by jaeandersson** [comment]
I double-checked: Indeed, the above persistent variable does get deleted by `clean all`:

``` matlab
>> SwigRef.SWIG_module_mem

ans =

     []

>> SwigRef.SWIG_module_mem(100)
>> SwigRef.SWIG_module_mem

ans =

   100

>> clear all
>> SwigRef.SWIG_module_mem

ans =

   100
```

**Comment by jaeandersson** [comment]
Another note: In principle, it should be possible to have modules unloaded. Apart from being prudent in general and clean up stuff when they are no longer needed, the main benefit of this as I see it is that you don't have to restart MATLAB every time you re-generate your SWIG bindings.  For it to work with the above scheme, an address to the `saved_swig_module` for each module would need to be stored in the module memory struct. That way, it can be updated when a module is unloaded.

**Comment by dcb210** [comment]
Yes, I’ve been pondering on how to resolve the calling overhead.

**Comment by dcb210** [comment]
I’ve been contemplating supporting mex unloading also.  However, the problem is non-trivial.  Currently, for dependent modules, SWIG maintains the type table by setting up a linked list to each static swig_module struct in each module.  This implementation requires that all dependent modules remain loaded for the current Matlab session because if a module unloads the linked list will contain pointers to structures that no longer exist in memory.  A work around would be to copy the swig_module to persistent Matlab memory when a module is loaded.  Then the linked lists are created using Matlab persistent memory.  At this point mex files are free to load or unload.  This type of implementation is tricky to design and maintain.  For instance, how do we publish the existence of the persistent Matlab memory to all modules?  Also, if the type information in a module changes, due to a change in the C/C++ code and then recompilation, then tries to reload, how do we update the linked list in persistent Matlab memory?  It’s a very complicated problem that I don’t have the time to support.

**Comment by jaeandersson** [comment]
Yes, unloading is tricky and IMO not critically important at this point. There is a function called when unloading mex file, it would have to implement the updating of all other modules. Anyway, it's not so important at this point - could be fixed later if deemed necessary.

**Comment by dcb210** [comment]
Do structs in C libraries also inherit SwigRef?  Also, I’m failing to see how we replace the global variable with a static method.  Currently all of the type information is loaded when we call ‘modulesetup.m’.  ‘modulesetup.m’ also loads the type information for all dependent modules by calling the module mex file with no arguments.  How do we encapsulate all of this functionality in a static class method?  The global variable is required as a means to publish the type information to all dependent modules.

**Comment by jaeandersson** [comment]
Proxy instances of C structs will inherit from SwigRef but it's besides the point. It's a static method so you don't need any instance. The SwigRef class is shared between all modules.

**Comment by jaeandersson** [comment]
Btw, I also think it would be prudent to remove the module load in `modulesetup.m`. This can be done from the mex file instead. I'll try to take time later today to do the merge and fix these things.

**Comment by dcb210** [comment]
I already attempted to create the module load from the mex file.  It’s not trivial.  The current module does not know the name of the mex file for the imported module, just the imported module name.  I solved the problem by having ‘modulesetup.m’ call ‘importedmodulesetup.m’.  This works well for our source which has 64 modules with multiple levels of dependency.  That will be fantastic if you can think of a way to encapsulate all of this in a static method that also handles the user defined SWIG_TYPE_TABLE value (for our source SWIG_TYPE_TABLE is the same for all modules but it could be different).  At the moment I don’t see how to implement the static method idea.

BTW I’m discovering a type problem that I think is related to the order that modules are loaded.  I have a std::vector of objects that is returning a SwigRef instead of the actual object type (SwigRef instead of package.obj which inherits SwigRef) when using the {} operator.  I believe that the modules need to be loaded in their order of dependency.  The current implementation does not do this.  I will attempt a fix to address this problem.

**Comment by jaeandersson** [comment]
Pull request merged. Instead of a static method in `SwigRef.m`, I opted for a separate file `SwigMem.m`. You might need to update your installation instructions accordingly.

**Comment by dcb210** [comment]
Nice work!  Note that I just created a pull request that fixes SWIG_Matlab_SetModule() & SWIG_Matlab_GetModule() so that they properly use SWIG_RUNTIME_VERSION & SWIG_TYPE_TABLE_NAME. Without this change SWIG wrapping for Matlab does not fully support modules.

**Comment by jaeandersson** [comment]
> I already attempted to create the module load from the mex file.  It’s not trivial.  The current module does not know the name of the mex file for the imported module, just the imported module name.

For us, I think the mex file name is always `modulenameMATLAB_wrap`. I think that's because we use CMake and `UseSWIG.cmake`. What if we changed the definition of `mex_fcn` in `matlab.cxx` from "C++ filename minus suffix" to "module name plus `MATLAB_wrap`"? Would this not work? If you build the wrapper with the `mex` command, I guess you might need to set the `-output` option then, but that shouldn't be a problem.

Cf. #44.

**Comment by dcb210** [comment]
That’s an assumption we can’t make.  Do to limitations we don’t use CMake’s UseSWIG.cmake but our own version that uses a different naming method.  We’re probably not alone in this respect.  I personally don’t have a problem with using ‘modulesetup.m’.  It’s seems like good reuse of an existing feature to support directors.  Perhaps the intent was to remove the use of ‘modulesetup.m’ at some future date?  If so perhaps this change can be addressed then?

**Comment by jaeandersson** [comment]
> That’s an assumption we can’t make.

What is? Why can't we decide that the name of the compiled mex-file follows some naming convention?

> Perhaps the intent was to remove the use of ‘modulesetup.m’ at some future date?

Yes, it's a bit of a hack IMO. I would feel much more comfortable with the modules communicating directly with each other. That would also allow us to use `mexCallMatlabWithTrap` instead of running a script.

**Comment by dcb210** [comment]
Correct, we can’t assume that the name of the mex file will always be modulenameMATLAB_wrap.  In our case it’s modulenameMatlab.

My initial attempt was to do as you propose, that is, use mexCallMatlabWithTrap to call the dependent mex directly but I discovered the mex naming assumption problem and implemented the current approach.  SWIG doesn’t know anything about the name of the wrapped c/c++ file, just the name of the imported module.  A work around would be to add a module option that includes the name of the mex file (similar to the package option http://www.swig.org/Doc3.0/SWIGDocumentation.html#Python_modulepackage http://www.swig.org/Doc3.0/SWIGDocumentation.html#Python_modulepackage) but my feeling is this work around is also a bit of a hack.  I suppose it boils down to deciding the hack to which the community of end-users is most comfortable :-)

**Comment by jaeandersson** [comment]
> Correct, we can’t assume that the name of the mex file will always be modulenameMATLAB_wrap.  In our case it’s modulenameMatlab

I don't follow the logic. As I see it, the name of the compiled module is whatever we decide it to be. Until now it has been the same as the C++ file (since that's convenient when compiling it using the mex command). Is the naming convention for the Python module not to name the module "_module.so"?

**Comment by dcb210** [comment]
It’s customizable by the end-user using the swig ‘-o’ option.  We can’t assume that it will always be a specific naming pattern.  As I’ve already pointed out, we’re using a different naming convention.

However, I think a better approach is to make a load function that resides within the Matlab package directory.  In this case we have complete control over the naming and we no longer rely on a setup script.

**Comment by jaeandersson** [comment]
> It’s customizable by the end-user using the swig ‘-o’ option

The '-o' options specifies the name of c++ file. As I see it, it doesn't specify the name of the compiled mex function.

**Comment by jaeandersson** [comment]
In my understanding, for Python you can set the `-o` to whatever you want when calling `swig`. But the compiled module should be called `_modulename.so`.

**Comment by jaeandersson** [comment]
I implemented the naming convention in a separate branch: 8f4101ff1f64d1cb397416ee4680a7fa9ab8b1a2

I cannot see what's wrong with this.

**Comment by dcb210** [comment]
It’s only a problem for multiple dependent modules.  The import directive gives us the name of the module not the name of the mex generated for the module.  For Matlab, not Python, the name of the mex file can be whatever we choose.  It doesn’t have to be ‘moduleMATLAB_wrap’.  The proxy classes generated by swig correctly call the mex file specified by the end-user.  If the end-user uses CMake’s UseSWIG.cmake it will be ‘moduleMATLAB_wrap’ otherwise it will be something totally different.  The proxy class calls the correct mex file whether it’s ‘moduleMATLAB_wrap’ or ‘weirdModuleNaming’.  The problem is that the %import directive doesn’t supply us with the ‘weirdModuleNaming’ name we need.  We just get ‘module’.

Python also allows wrapping without a proxy class.  To my knowledge that’s not an option for Matlab at the moment.

**Comment by jaeandersson** [comment]
> If the end-user uses CMake’s UseSWIG.cmake it will be ‘moduleMATLAB_wrap’ otherwise it will be something totally different.

The assumption is of course that the user's build system also follows this naming convention. This particular choice was made since it agrees with `UseSWIG.cmake`. If you compile from the MATLAB command line you have to set the `-output` flag, e.g.:

``` matlab
mex -output mymoduleMATLAB_wrap mycppsourcefilefromswig.cxx
```

**Comment by dcb210** [comment]
That’s the point I’ve been trying to make.  SWIG should not be imposing naming conventions.  It should be chosen by the end-user.  Currently it works as intended.  If we impose the ‘moduleMATLAB_wrap’ naming convention then it will break alternate build systems chosen by the end-user.

I personally think the ‘module.load’ method is the route to take.  We can then abandon the ‘modulesetup.m’ scripts altogether.  However, at the moment ‘modulesetup.m’ seems to work well and I will be content if it doesn’t change.

**Comment by jaeandersson** [comment]
There is always a naming convention. The current naming convention, to have the compiled mex file match its source, was chosen by me when I wrote that piece of code. I picked that convention because it made it trivial to compile from MATLAB's command line. But I don't understand why we have to stick with it.
I'll send a mail to the mailing list asking about this.

**Comment by dcb210** [comment]
That’s correct, there is a naming convention.  For Matlab the mex file name has to be different than the Matlab package name, which is usually the module name.  Otherwise you’ll end up with name conflicts.

**Comment by jaeandersson** [comment]
> That’s correct, there is a naming convention.  For Matlab the mex file name has to be different than the Matlab package name, which is usually the module name.

Right. This disqualifies `module.mexsuffix`. Python's convention `_module.mexsuffix` is also not possible since you can't have MATLAB functions starting with underscore. Realistic possibilities would be `module_wrap.mexsuffix` (used currently in SWIG's test suite) and `moduleMATLAB_wrap.mexsuffix` (used by UseSWIG.cmake). I prefer the latter since it avoids name conflicts when you generate modules to multiple languages.

**Comment by jaeandersson** [comment]
It would be easy to add some option to SWIG to replace the `MATLAB_wrap` infix with something else. But the assumption would be that you use the same infix for all interdependent modules.

**Comment by jgillis** [comment]
While you're sorting out this issue/choice, perhaps I could addd another dimension: https://github.com/casadi/casadi/issues/1477

**Comment by jaeandersson** [comment]
> While you're sorting out this issue/choice, perhaps I could addd another dimension: casadi/casadi#1477

I don't follow. From what I can tell, we support `SWIG_TYPE_TABLE` after the latest fixes by @dcb210.

**Comment by dcb210** [comment]
Actually, it’s too long.  In my case, I’d end up with ‘moduleMatlabMATLAB_wrap’.  I’d prefer something shorter similar to Python.  Couldn’t we just move the underscore to the end?

‘module_’
‘moduleMatlab_’ for me
‘moduleMATLAB_wrap_’ for UseSWIG.cmake

That solves the naming convention problem but it doesn’t address the issue of module imports.  How do we know if we have ‘module_’, ‘moduleMatlab_’, or ‘moduleMATLAB_wrap_’?  Like I mentioned before, all we get from the import is ‘module’.  Python uses it’s own native import mechanisms to load SWIG modules.  In Matlab we have no native import mechanism (to clarify there is an import command, but it just supports importing packages into the path it doesn’t load any modules).  We have to create our own mechanism.  That’s why I proposes one of the following:
1. Use an option to the %module command similar to %module(package=“name”) in Python.
2. Create our own ‘module.load’ function.

I prefer 2.

**Comment by jaeandersson** [comment]
If you have an option for replacing the infix with something else, then you can set it to `_`. The only thing is that you have to do so for all modules you want link together. I don't think that's too much to ask for.
I don't understand your `module.load` suggestion. Do you want to place a function called "load" in the +module directory?

**Comment by dcb210** [comment]
I was implying that the infix be somewhat more automatic like Python, but that doesn’t resolve the problem of loading modules.  It only resolves the issue of an end-user inadvertently creating a mex with name ‘module.mex’.  These are 2 separate issues.
1. Create infix to eliminate the possibility of name conflicts between Matlab package and mex file.
2. Loading modules without using ‘modulesetup.m’
   a. Currently to load modules ‘modulesetup.m’ does the following:
       1. Calls ‘importmodulesetup.m’ for all imported modules.
               2. Calls ‘moduleMatlab.mex’ or ‘moduleMATLAB_wrap.mex’ (whatever wrapped filename was chosen) with no arguments to load the type table for itself.
           i. Note that this results in a single recursive call to itself but it also ensures that all other modules are loaded via the calls to ‘importedmodulesetup.m’.  Also it exits cleanly without infinite recursion.
   b. To eliminate the use of ‘modulesetup.m’ I proposed the following:
       1. Use an option to the %module command similar to %module(package=“name”) in Python.
           i. This option would designate the name of the mex file which is not available to us via an import. Note that this is not the infix, it’s the final name after the infix is applied.  As I stated previously we can’t know the name of the wrapped file via an import.
               2. Create our own ‘module.load’ function.
           i. This function resides in the package but performs the same function as ‘modulesetup.m’. It calls ‘importedmodule.load’ before calling ‘moduleMatlab.mex’ or ‘moduleMATLAB_wrap.mex’.

Does this make sense now?

**Comment by jaeandersson** [comment]
I added another commit to the branch: 72c5ccb20c30e049fa4426566211500534eeca5c. This now includes an option ("-mexinfix") of setting an infix. By default, the infix is `_wrap`, but the user can redefine it to be something else, including "_" or nothing at all. For CasADi's CMake, I had to add the line:

```
set(SWIG_MODULE_casadiMATLAB_wrap_EXTRA_FLAGS "-mexinfix" "MATLAB_wrap")
```

I think that this is cleaner than the existing convention (relying on the c++ file name). Would you mind if propagate these changes to the master branch?

As for the elimination of `modulesetup.m`, I have to think a bit more about it. I'm afraid I don't understand all of your reasoning above. I was planning to look at multiple modules in the coming days anyway, for a project that uses CasADi as an external module. Afterwards, I could have a look at this again.

**Comment by dcb210** [comment]
It seems like a reasonable change.  It is a deviation, perhaps needed, from other languages.  Python probably ought to provide a similar option instead of the automatic “_” prefix.  However, my thought is the change will end up being a point of confusion for others coming from other SWIG languages instead of a driver for a better way of specifying the infix.  I can deal with the change if others agree. 

Yes, please examine the code.  My explanations will make more sense once you examine the source.  In particular follow the setup_imports variable in matlab.cxx to see its usage.

**Comment by jaeandersson** [comment]
I had a look at the implementation and for me it looks like it mixes up the package name and the module name. My understanding was that you can have multiple modules all part of the same package.

I refactored it a bit and implemented the communication using `mexCallMATLABWithTrap` that I suggested above: 90e792fd10a010f73bd44daa07d4fdbd0b4b54ec (it's in a separate branch). I tried it out with a trivial project with multiple modules and it works fine from what I can tell. It also restores the previous behaviour with the mex-file calling the setup script but never the other way around.

Just to make sure that we don't speak past each other: Can you confirm that the design in 90e792fd10a010f73bd44daa07d4fdbd0b4b54ec is somehow unsafe? Because I cannot see why.

**Comment by jaeandersson** [comment]
Changes pushed to my "matlab" branch.

**Pull request merged**
