### PR TITLE
matlab: fixed -outdir support

### PR DESCRIPTION
**Pull request by tesch1**
fix for issue #1

### CODE REVIEW

**Comment by tesch1** [comment]
weird, I only wanted to add up through 73b8669 as a pull request.

**Comment by fabiencastan** [comment]
@tesch1 you need to create a dedicated branch for each pull request.
Thanks for fixing the issue #1!

**Comment by tesch1** [comment]
aaha!  ok, now I get it.  I'll do that in the future.  So, in the meantime, would it be alright to use this pull-request as a fix for both issues #1 and #3?

**Comment by jaeandersson** [comment]
Great, thanks for your contribution!

**Pull request merged**
